# # prometheus.yml
# scrape_configs:
#   # Scrape Prometheus itself
#   - job_name: "prometheus"
#     static_configs:
#       - targets: ["prometheus:9090"]

#   # Scrape FastAPI app metrics
#   - job_name: "fastapi_app"
#     static_configs:
#       - targets: ["localhost:8008"]  # Remplacez par le nom du service Docker du conteneur FastAPI

#   # Scrape APScheduler metrics
#   - job_name: "apscheduler"
#     static_configs:
#       - targets: ["localhost:8009"]  # Remplacez 'localhost' par le nom du service Docker FastAPI


global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['prometheus:9090']

  - job_name: 'fastapi'
    static_configs:
      - targets: ['host.docker.internal:8000']  # Accède à FastAPI en local depuis Docker

