# app/docker-compose.yml

services:
  # app:
  #   build:
  #     context: ..
  #     dockerfile: ./app/Dockerfile
  #   container_name: fastapi_web
  #   restart: always
  #   command: uvicorn main:app --host ${FASTAPI_HOST} --port ${FASTAPI_PORT}
  #   environment:
  #     - PYTHONPATH=/app
  #     - POSTGRES_HOST=localhost:9092
  #     - KAFKA_BOOTSTRAP_SERVERS=${KAFKA_BOOTSTRAP_SERVERS}
  #     - DATABASE_URL=${DATABASE_URL}
  #     - DEBUG=${DEBUG}
  #   volumes:
  #     - ../app:/app
  #     - ../alembic.ini:/app/alembic.ini
  #     - ../alembic:/app/alembic
  #   ports:
  #     - "${FASTAPI_PORT}:${FASTAPI_PORT}"
  #   env_file:
  #     - ../app/.env
  #   networks:
  #     - shared_network


  prometheus:
    image: prom/prometheus
    container_name: prometheus_api
    volumes:
      - ../prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"
    networks:
      - shared_network

  grafana:
    image: grafana/grafana
    container_name: grafana
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
    volumes:
      - grafana-storage:/var/lib/grafana
    networks:
      - shared_network
    depends_on:
      - prometheus

volumes:
  app-data:
    driver: local  # Stockage pour les textes extraits des vidéos
  grafana-storage:
    driver: local

networks:
  shared_network:
    external: true
