# db/docker-compose.yml

services:
  dbsql:
    image: postgres:13
    container_name: db_postgres
    restart: always
    env_file:
      - .env
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "5432:5432"
    networks:
      - shared_network

  adminer:
    image: adminer
    container_name: adminer
    env_file:
      - .env
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "8080:8080"
    networks:
      - shared_network


  redis:
    image: redis:alpine
    container_name: redis_cache
    restart: always
    ports:
      - "6379:6379"
    networks:
      - shared_network

  minio:
    image: minio/minio
    container_name: minio
    env_file:
      - .env
    environment:
      MINIO_ROOT_USER: ${MINIO_ACCESS_KEY}
      MINIO_ROOT_PASSWORD: ${MINIO_SECRET_KEY}
    ports:
      - "9000:9000"  
      - "9001:9001"  # Console d'administration (facultatif)
    command: server /data --console-address ":9001"
    volumes:
      - minio_data:/data
    networks:
      - shared_network


volumes:
  postgres_data:
    driver: local
  minio_data:
    driver: local

networks:
  shared_network:
    external: true